# Global settings
tag_prefix = "v"
from_latest_tag = true
ignore_merge_commits = true
ignore_fixup_commits = true
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
branch_whitelist = ["main"]
skip_ci = "[skip ci]"
skip_untracked = false

pre_bump_hooks = [
    "cargo fmt --check",
    "cargo clippy --workspace --all-targets --all-features -- -D warnings",
    "cargo check --workspace",
    "cargo test --workspace",
    "cargo build --release --workspace",
    "echo 'bumping from {{latest|0.0.0}} to {{version|0.0.1}}'",
]

post_bump_hooks = [
    "git push",
    "git push origin {{version}}",
]

pre_package_bump_hooks = [
    "echo 'upgrading {{package}} to {{version}}'",
]

post_package_bump_hooks = [
    "cargo check -p {{package}}",
]

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
cog verify --file $1
"""

[git_hooks.pre-push]
script = """#!/bin/sh
set -e
cog check
"""

[commit_types]
feat = { changelog_title = "Features" }
fix = { changelog_title = "Bug Fixes" }
docs = { changelog_title = "Documentation", omit_from_changelog = true }
chore = { changelog_title = "Miscellaneous", omit_from_changelog = true }
refactor = { changelog_title = "Refactoring" }
perf = { changelog_title = "Performance" }
test = { changelog_title = "Testing", omit_from_changelog = true }
ci = { changelog_title = "CI/CD", omit_from_changelog = true }
build = { changelog_title = "Build", omit_from_changelog = true }
style = { changelog_title = "Style", omit_from_changelog = true }

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "crowdcontrol"
owner = "wadefletch"
authors = [
    { signature = "wadefletcher", username = "wadefletch" }
]

[bump_profiles]

[packages]
crowdcontrol-core = { path = "crowdcontrol-core", public_api = true, bump_order = 1 }
crowdcontrol-cli = { path = "crowdcontrol-cli", public_api = true, bump_order = 2 }
