# Cargo configuration for CrowdControl project

[alias]
# Run only the Docker integration tests (requires Docker)
test-integration = "test --test integration_test -- --ignored --test-threads=1"

# Run all Docker-dependent tests including user journey tests (requires Docker)
test-docker = "test -- --ignored --test-threads=1"
