// TDD: Tests for Agent-Repo association
// Run with: cargo test --package crowdcontrol-core --test agent_repo_tests

use anyhow::Result;
use chrono::Utc;
use crowdcontrol_core::{
    agent::{load_agent_metadata, save_agent_metadata, AgentMetadata},
    Agent, AgentStatus, Config,
};
use std::fs;
use tempfile::TempDir;

fn create_test_config() -> (Config, TempDir) {
    let temp_dir = tempfile::tempdir().unwrap();
    let config = Config {
        workspaces_dir: temp_dir.path().to_path_buf(),
        image: "crowdcontrol:latest".to_string(),
        verbose: 0,
        default_memory: None,
        default_cpus: None,
    };
    (config, temp_dir)
}

#[test]
fn test_agent_has_repo_slug_field() {
    let agent = Agent {
        name: "myapp-main".to_string(),
        status: AgentStatus::Created,
        container_id: None,
        repository: "git@github.com:org/myapp.git".to_string(),
        branch: Some("main".to_string()),
        created_at: Utc::now(),
        workspace_path: "/tmp/test".into(),
        repo_slug: Some("myapp".to_string()),
    };

    assert_eq!(agent.repo_slug, Some("myapp".to_string()));
}

#[test]
fn test_agent_without_repo_slug() {
    // Backwards compatibility: agents created with URL directly
    let agent = Agent {
        name: "standalone-agent".to_string(),
        status: AgentStatus::Created,
        container_id: None,
        repository: "git@github.com:org/repo.git".to_string(),
        branch: None,
        created_at: Utc::now(),
        workspace_path: "/tmp/test".into(),
        repo_slug: None,
    };

    assert_eq!(agent.repo_slug, None);
}

#[test]
fn test_save_and_load_agent_with_repo_slug() -> Result<()> {
    let (config, _temp_dir) = create_test_config();
    let agent_name = "myapp-main";
    let workspace_path = config.agent_workspace_path(agent_name);
    fs::create_dir_all(&workspace_path)?;

    let agent = Agent {
        name: agent_name.to_string(),
        status: AgentStatus::Created,
        container_id: None,
        repository: "git@github.com:org/myapp.git".to_string(),
        branch: Some("main".to_string()),
        created_at: Utc::now(),
        workspace_path: workspace_path.clone(),
        repo_slug: Some("myapp".to_string()),
    };

    save_agent_metadata(&config, &agent)?;

    let loaded = load_agent_metadata(&config, agent_name)?;
    assert_eq!(loaded.repo_slug, Some("myapp".to_string()));

    Ok(())
}

#[test]
fn test_save_and_load_agent_without_repo_slug() -> Result<()> {
    let (config, _temp_dir) = create_test_config();
    let agent_name = "standalone";
    let workspace_path = config.agent_workspace_path(agent_name);
    fs::create_dir_all(&workspace_path)?;

    let agent = Agent {
        name: agent_name.to_string(),
        status: AgentStatus::Created,
        container_id: None,
        repository: "git@github.com:org/repo.git".to_string(),
        branch: None,
        created_at: Utc::now(),
        workspace_path: workspace_path.clone(),
        repo_slug: None,
    };

    save_agent_metadata(&config, &agent)?;

    let loaded = load_agent_metadata(&config, agent_name)?;
    assert_eq!(loaded.repo_slug, None);

    Ok(())
}

#[test]
fn test_legacy_metadata_loads_with_none_repo_slug() -> Result<()> {
    // Simulate loading metadata that was saved before repo_slug existed
    let (config, _temp_dir) = create_test_config();
    let agent_name = "legacy-agent";
    let workspace_path = config.agent_workspace_path(agent_name);
    let metadata_dir = workspace_path.join(".crowdcontrol");
    fs::create_dir_all(&metadata_dir)?;

    // Write legacy metadata JSON without repo_slug field
    let legacy_json = r#"{
        "_comment": "This file is auto-generated by CrowdControl. Do not edit manually.",
        "name": "legacy-agent",
        "repository": "git@github.com:org/legacy.git",
        "branch": "main",
        "created_at": "2024-01-01T00:00:00Z",
        "container_id": null
    }"#;

    fs::write(metadata_dir.join("metadata.json"), legacy_json)?;

    // Should load successfully with repo_slug = None
    let loaded = load_agent_metadata(&config, agent_name)?;
    assert_eq!(loaded.repo_slug, None);
    assert_eq!(loaded.repository, "git@github.com:org/legacy.git");

    Ok(())
}

#[test]
fn test_agent_metadata_includes_repo_slug() {
    // Verify AgentMetadata struct has repo_slug field
    let metadata = AgentMetadata {
        comment: "test".to_string(),
        name: "test".to_string(),
        repository: "git@github.com:org/test.git".to_string(),
        branch: None,
        created_at: Utc::now(),
        container_id: None,
        repo_slug: Some("test".to_string()),
    };

    assert_eq!(metadata.repo_slug, Some("test".to_string()));
}

#[test]
fn test_agent_display_name_with_repo() {
    let agent = Agent {
        name: "myapp-main".to_string(),
        status: AgentStatus::Created,
        container_id: None,
        repository: "git@github.com:org/myapp.git".to_string(),
        branch: Some("main".to_string()),
        created_at: Utc::now(),
        workspace_path: "/tmp/test".into(),
        repo_slug: Some("myapp".to_string()),
    };

    // Display name should be "repo:label" format
    assert_eq!(agent.display_name(), "myapp:main");
}

#[test]
fn test_agent_display_name_without_repo() {
    let agent = Agent {
        name: "standalone-agent".to_string(),
        status: AgentStatus::Created,
        container_id: None,
        repository: "git@github.com:org/repo.git".to_string(),
        branch: None,
        created_at: Utc::now(),
        workspace_path: "/tmp/test".into(),
        repo_slug: None,
    };

    // Without repo, display name is just the name
    assert_eq!(agent.display_name(), "standalone-agent");
}

#[test]
fn test_agent_label() {
    // Agent created with repo:label format
    let agent = Agent {
        name: "myapp-main".to_string(), // filesystem name
        status: AgentStatus::Created,
        container_id: None,
        repository: "git@github.com:org/myapp.git".to_string(),
        branch: Some("main".to_string()),
        created_at: Utc::now(),
        workspace_path: "/tmp/test".into(),
        repo_slug: Some("myapp".to_string()),
    };

    // Label should extract just the "main" part
    assert_eq!(agent.label(), "main");
}

#[test]
fn test_agent_label_without_repo() {
    let agent = Agent {
        name: "standalone-agent".to_string(),
        status: AgentStatus::Created,
        container_id: None,
        repository: "git@github.com:org/repo.git".to_string(),
        branch: None,
        created_at: Utc::now(),
        workspace_path: "/tmp/test".into(),
        repo_slug: None,
    };

    // Without repo, label is the full name
    assert_eq!(agent.label(), "standalone-agent");
}
