use anyhow::{anyhow, Context, Result};
use chrono::{DateTime, Utc};
use fs2::FileExt;
use serde::{Deserialize, Serialize};
use std::fs::{self, OpenOptions};
use std::io::{Read, Seek, Write};
use std::path::PathBuf;
use std::process::Command;
use tracing::{debug, info, trace};

use crate::{Agent, AgentStatus, Config};

#[derive(Debug, Serialize, Deserialize)]
pub struct AgentMetadata {
    #[serde(rename = "_comment")]
    pub comment: String,
    pub name: String,
    pub repository: String,
    pub branch: Option<String>,
    pub created_at: DateTime<Utc>,
    pub container_id: Option<String>,
}

pub fn save_agent_metadata(config: &Config, agent: &Agent) -> Result<()> {
    let metadata_path = config
        .agent_workspace_path(&agent.name)
        .join(".crowdcontrol")
        .join("metadata.json");

    debug!(
        "Saving metadata for agent '{}' to {:?}",
        agent.name, metadata_path
    );

    // Ensure parent directory exists
    if let Some(parent) = metadata_path.parent() {
        trace!("Creating parent directory: {:?}", parent);
        fs::create_dir_all(parent)?;
    }

    let metadata = AgentMetadata {
        comment: "This file is auto-generated by CrowdControl. Do not edit manually.".to_string(),
        name: agent.name.clone(),
        repository: agent.repository.clone(),
        branch: agent.branch.clone(),
        created_at: agent.created_at,
        container_id: agent.container_id.clone(),
    };

    let json = serde_json::to_string_pretty(&metadata)?;

    // Open file with write/create permissions
    let mut file = OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .open(&metadata_path)
        .with_context(|| format!("Failed to open metadata file: {:?}", metadata_path))?;

    // Lock file exclusively for writing
    trace!("Acquiring exclusive lock on metadata file");
    file.lock_exclusive().with_context(|| {
        format!(
            "Failed to acquire lock on metadata file: {:?}",
            metadata_path
        )
    })?;

    // Write the data
    let write_result = file
        .write_all(json.as_bytes())
        .with_context(|| format!("Failed to write agent metadata to {:?}", metadata_path));

    // Always unlock, even if write failed
    trace!("Releasing lock on metadata file");
    file.unlock()
        .with_context(|| format!("Failed to unlock metadata file: {:?}", metadata_path))?;

    write_result?;
    debug!("Successfully saved metadata for agent '{}'", agent.name);
    Ok(())
}

pub fn load_agent_metadata(config: &Config, name: &str) -> Result<Agent> {
    let workspace_path = config.agent_workspace_path(name);
    let metadata_path = workspace_path.join(".crowdcontrol").join("metadata.json");

    debug!(
        "Loading metadata for agent '{}' from {:?}",
        name, metadata_path
    );

    if !metadata_path.exists() {
        debug!("Metadata file not found for agent '{}'", name);
        return Err(anyhow!("Agent '{}' not found", name));
    }

    // Open file for reading
    let mut file = OpenOptions::new()
        .read(true)
        .open(&metadata_path)
        .with_context(|| format!("Failed to open metadata file: {:?}", metadata_path))?;

    // Lock file shared for reading (multiple readers allowed)
    file.lock_shared().with_context(|| {
        format!(
            "Failed to acquire lock on metadata file: {:?}",
            metadata_path
        )
    })?;

    // Read the contents
    let mut json = String::new();
    let read_result = file
        .read_to_string(&mut json)
        .with_context(|| format!("Failed to read agent metadata from {:?}", metadata_path));

    // Always unlock, even if read failed
    file.unlock()
        .with_context(|| format!("Failed to unlock metadata file: {:?}", metadata_path))?;

    read_result?;

    let metadata: AgentMetadata =
        serde_json::from_str(&json).with_context(|| "Failed to parse agent metadata")?;

    Ok(Agent {
        name: metadata.name,
        status: AgentStatus::Created,
        container_id: metadata.container_id,
        repository: metadata.repository,
        branch: metadata.branch,
        created_at: metadata.created_at,
        workspace_path,
    })
}

pub fn list_all_agents(config: &Config) -> Result<Vec<String>> {
    let mut agents = Vec::new();

    if !config.workspaces_dir.exists() {
        return Ok(agents);
    }

    for entry in fs::read_dir(&config.workspaces_dir)? {
        let entry = entry?;
        let path = entry.path();

        if path.is_dir() {
            let metadata_path = path.join(".crowdcontrol").join("metadata.json");
            if metadata_path.exists() {
                if let Some(name) = path.file_name() {
                    agents.push(name.to_string_lossy().to_string());
                }
            }
        }
    }

    Ok(agents)
}

/// Update agent metadata atomically with file locking
/// This function loads the current metadata, applies the update function, and saves it back
pub fn update_agent_metadata<F>(config: &Config, name: &str, update_fn: F) -> Result<()>
where
    F: FnOnce(&mut Agent) -> Result<()>,
{
    let workspace_path = config.agent_workspace_path(name);
    let metadata_path = workspace_path.join(".crowdcontrol").join("metadata.json");

    if !metadata_path.exists() {
        return Err(anyhow!("Agent '{}' not found", name));
    }

    // Open file for read/write
    let mut file = OpenOptions::new()
        .read(true)
        .write(true)
        .open(&metadata_path)
        .with_context(|| format!("Failed to open metadata file: {:?}", metadata_path))?;

    // Lock file exclusively for the entire operation
    file.lock_exclusive().with_context(|| {
        format!(
            "Failed to acquire lock on metadata file: {:?}",
            metadata_path
        )
    })?;

    // Read current data
    let mut json = String::new();
    file.read_to_string(&mut json)?;

    let metadata: AgentMetadata =
        serde_json::from_str(&json).with_context(|| "Failed to parse agent metadata")?;

    // Create agent from metadata
    let mut agent = Agent {
        name: metadata.name,
        status: AgentStatus::Created,
        container_id: metadata.container_id,
        repository: metadata.repository,
        branch: metadata.branch,
        created_at: metadata.created_at,
        workspace_path: workspace_path.clone(),
    };

    // Apply the update
    update_fn(&mut agent)?;

    // Convert back to metadata
    let updated_metadata = AgentMetadata {
        comment: "This file is auto-generated by CrowdControl. Do not edit manually.".to_string(),
        name: agent.name.clone(),
        repository: agent.repository.clone(),
        branch: agent.branch.clone(),
        created_at: agent.created_at,
        container_id: agent.container_id.clone(),
    };

    let updated_json = serde_json::to_string_pretty(&updated_metadata)?;

    // Truncate and rewrite the file
    file.set_len(0)?;
    file.seek(std::io::SeekFrom::Start(0))?;
    file.write_all(updated_json.as_bytes())?;

    // Unlock the file
    file.unlock()?;

    Ok(())
}

pub fn validate_agent_name(name: &str) -> Result<()> {
    if name.is_empty() {
        return Err(anyhow!("Agent name cannot be empty"));
    }

    if !name
        .chars()
        .all(|c| c.is_alphanumeric() || c == '-' || c == '_')
    {
        return Err(anyhow!(
            "Agent name can only contain alphanumeric characters, hyphens, and underscores"
        ));
    }

    if name.len() > 64 {
        return Err(anyhow!("Agent name must be 64 characters or less"));
    }

    Ok(())
}

pub fn clone_repository(
    repository: &str,
    target_path: &PathBuf,
    branch: Option<&str>,
) -> Result<()> {
    let mut cmd = Command::new("git");
    cmd.arg("clone");

    if let Some(branch_name) = branch {
        cmd.arg("-b").arg(branch_name);
        info!(
            "Cloning repository {} (branch: {}) to {:?}",
            repository, branch_name, target_path
        );
    } else {
        info!("Cloning repository {} to {:?}", repository, target_path);
    }

    cmd.arg(repository).arg(target_path);

    debug!("Executing git command: {:?}", cmd);
    let output = cmd.output().context("Failed to execute git clone")?;

    if !output.status.success() {
        let stderr = String::from_utf8_lossy(&output.stderr);
        return Err(anyhow!("Failed to clone repository: {}", stderr));
    }

    debug!("Repository cloned successfully");
    Ok(())
}

pub fn verify_repository_setup(workspace_path: &PathBuf) -> Result<bool> {
    // Repository is now cloned directly to workspace root, so check for .crowdcontrol there
    let crowdcontrol_dir = workspace_path.join(".crowdcontrol");
    Ok(crowdcontrol_dir.exists())
}

pub fn format_duration(created_at: DateTime<Utc>) -> String {
    let now = Utc::now();
    let duration = now.signed_duration_since(created_at);

    if duration.num_days() > 0 {
        format!("{}d ago", duration.num_days())
    } else if duration.num_hours() > 0 {
        format!("{}h ago", duration.num_hours())
    } else if duration.num_minutes() > 0 {
        format!("{}m ago", duration.num_minutes())
    } else {
        "just now".to_string()
    }
}

/// Auto-repair function to clear stale container IDs from agent metadata
pub async fn auto_repair_stale_container_id(config: &Config, agent_name: &str) -> Result<()> {
    use crate::DockerClient;

    // Load current agent metadata
    let agent = load_agent_metadata(config, agent_name)?;

    if let Some(container_id) = &agent.container_id {
        // Create Docker client to validate container ID
        let docker = DockerClient::new(config.clone())?;

        // Check if container ID is still valid
        if !docker
            .validate_container_id(agent_name, container_id)
            .await?
        {
            // Container ID is stale, clear it
            update_agent_metadata(config, agent_name, |agent| {
                debug!(
                    "Auto-repairing stale container ID for agent '{}'",
                    agent_name
                );
                agent.container_id = None;
                Ok(())
            })?;
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_config_with_dir;
    use std::sync::{Arc, Barrier};
    use std::thread;
    use tempfile::tempdir;

    fn create_test_config() -> (Config, tempfile::TempDir) {
        let temp_dir = tempdir().unwrap();
        let config = test_config_with_dir(temp_dir.path());
        (config, temp_dir)
    }

    fn create_test_agent(name: &str) -> Agent {
        Agent {
            name: name.to_string(),
            status: AgentStatus::Created,
            container_id: Some("test-container-id".to_string()),
            repository: "https://github.com/test/repo.git".to_string(),
            branch: Some("main".to_string()),
            created_at: Utc::now(),
            workspace_path: PathBuf::from("/test/workspace"),
        }
    }

    #[test]
    fn test_save_and_load_metadata() {
        let (config, _temp_dir) = create_test_config();
        let agent = create_test_agent("test-agent");

        // Save metadata
        save_agent_metadata(&config, &agent).unwrap();

        // Load metadata
        let loaded_agent = load_agent_metadata(&config, "test-agent").unwrap();

        assert_eq!(loaded_agent.name, agent.name);
        assert_eq!(loaded_agent.repository, agent.repository);
        assert_eq!(loaded_agent.branch, agent.branch);
        assert_eq!(loaded_agent.container_id, agent.container_id);
    }

    #[test]
    fn test_metadata_has_comment() {
        let (config, _temp_dir) = create_test_config();
        let agent = create_test_agent("test-agent");

        // Save metadata
        save_agent_metadata(&config, &agent).unwrap();

        // Read the raw JSON to verify comment field
        let metadata_path = config
            .agent_workspace_path("test-agent")
            .join(".crowdcontrol")
            .join("metadata.json");

        let content = std::fs::read_to_string(metadata_path).unwrap();
        assert!(content.contains("\"_comment\":"));
        assert!(content.contains("auto-generated"));
    }

    #[test]
    fn test_concurrent_reads() {
        let (config, _temp_dir) = create_test_config();
        let agent = create_test_agent("concurrent-read-test");

        // Save initial metadata
        save_agent_metadata(&config, &agent).unwrap();

        let config = Arc::new(config);
        let barrier = Arc::new(Barrier::new(5));
        let mut handles = vec![];

        // Spawn multiple threads to read simultaneously
        for i in 0..5 {
            let config = Arc::clone(&config);
            let barrier = Arc::clone(&barrier);

            let handle = thread::spawn(move || {
                barrier.wait();

                // All threads try to read at the same time
                let result = load_agent_metadata(&config, "concurrent-read-test");

                // Verify the read was successful
                let agent = result.expect(&format!("Thread {} failed to read", i));
                assert_eq!(agent.name, "concurrent-read-test");
                assert_eq!(agent.repository, "https://github.com/test/repo.git");
            });

            handles.push(handle);
        }

        // Wait for all threads to complete
        for handle in handles {
            handle.join().unwrap();
        }
    }

    #[test]
    fn test_concurrent_writes_are_serialized() {
        let (config, _temp_dir) = create_test_config();
        let config = Arc::new(config);
        let barrier = Arc::new(Barrier::new(3));
        let mut handles = vec![];

        // Create different agents to write
        for i in 0..3 {
            let config = Arc::clone(&config);
            let barrier = Arc::clone(&barrier);

            let handle = thread::spawn(move || {
                let agent = Agent {
                    name: format!("write-test-{}", i),
                    status: AgentStatus::Created,
                    container_id: Some(format!("container-{}", i)),
                    repository: format!("https://github.com/test/repo{}.git", i),
                    branch: Some("main".to_string()),
                    created_at: Utc::now(),
                    workspace_path: PathBuf::from(format!("/test/workspace{}", i)),
                };

                barrier.wait();

                // All threads try to write at the same time
                save_agent_metadata(&config, &agent).unwrap();
            });

            handles.push(handle);
        }

        // Wait for all threads to complete
        for handle in handles {
            handle.join().unwrap();
        }

        // Verify all agents were saved correctly
        for i in 0..3 {
            let agent = load_agent_metadata(&config, &format!("write-test-{}", i)).unwrap();
            assert_eq!(
                agent.repository,
                format!("https://github.com/test/repo{}.git", i)
            );
            assert_eq!(agent.container_id, Some(format!("container-{}", i)));
        }
    }

    #[test]
    fn test_atomic_update() {
        let (config, _temp_dir) = create_test_config();
        let agent = create_test_agent("update-test");

        // Save initial metadata
        save_agent_metadata(&config, &agent).unwrap();

        // Update metadata atomically
        update_agent_metadata(&config, "update-test", |agent| {
            agent.container_id = Some("new-container-id".to_string());
            agent.status = AgentStatus::Running;
            Ok(())
        })
        .unwrap();

        // Verify the update
        let updated_agent = load_agent_metadata(&config, "update-test").unwrap();
        assert_eq!(
            updated_agent.container_id,
            Some("new-container-id".to_string())
        );
    }

    #[test]
    fn test_concurrent_updates() {
        let (config, _temp_dir) = create_test_config();
        let agent = create_test_agent("concurrent-update-test");

        // Save initial metadata
        save_agent_metadata(&config, &agent).unwrap();

        let config = Arc::new(config);
        let barrier = Arc::new(Barrier::new(5));
        let mut handles = vec![];

        // Spawn multiple threads to update simultaneously
        for i in 0..5 {
            let config = Arc::clone(&config);
            let barrier = Arc::clone(&barrier);

            let handle = thread::spawn(move || {
                barrier.wait();

                // Each thread tries to update the container_id
                update_agent_metadata(&config, "concurrent-update-test", |agent| {
                    agent.container_id = Some(format!("container-from-thread-{}", i));
                    Ok(())
                })
                .unwrap();
            });

            handles.push(handle);
        }

        // Wait for all threads to complete
        for handle in handles {
            handle.join().unwrap();
        }

        // Verify that one of the updates succeeded and the data is consistent
        let final_agent = load_agent_metadata(&config, "concurrent-update-test").unwrap();
        assert!(final_agent.container_id.is_some());
        assert!(final_agent
            .container_id
            .unwrap()
            .starts_with("container-from-thread-"));
    }

    #[test]
    fn test_update_nonexistent_agent() {
        let (config, _temp_dir) = create_test_config();

        // Try to update a non-existent agent
        let result = update_agent_metadata(&config, "nonexistent", |agent| {
            agent.container_id = Some("should-not-work".to_string());
            Ok(())
        });

        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("not found"));
    }

    #[test]
    fn test_list_all_agents() {
        let (config, _temp_dir) = create_test_config();

        // Create multiple agents
        for i in 0..3 {
            let agent = create_test_agent(&format!("list-test-{}", i));
            save_agent_metadata(&config, &agent).unwrap();
        }

        // List all agents
        let agents = list_all_agents(&config).unwrap();

        assert_eq!(agents.len(), 3);
        assert!(agents.contains(&"list-test-0".to_string()));
        assert!(agents.contains(&"list-test-1".to_string()));
        assert!(agents.contains(&"list-test-2".to_string()));
    }

    #[test]
    fn test_mixed_concurrent_operations() {
        let (config, _temp_dir) = create_test_config();
        let agent = create_test_agent("mixed-ops-test");

        // Save initial metadata
        save_agent_metadata(&config, &agent).unwrap();

        let config = Arc::new(config);
        let barrier = Arc::new(Barrier::new(10));
        let mut handles = vec![];

        // Mix of readers and writers
        for i in 0..10 {
            let config = Arc::clone(&config);
            let barrier = Arc::clone(&barrier);

            let handle = if i % 2 == 0 {
                // Reader thread
                thread::spawn(move || {
                    barrier.wait();

                    let agent = load_agent_metadata(&config, "mixed-ops-test").unwrap();
                    assert_eq!(agent.name, "mixed-ops-test");
                })
            } else {
                // Writer thread
                thread::spawn(move || {
                    barrier.wait();

                    update_agent_metadata(&config, "mixed-ops-test", |agent| {
                        agent.container_id = Some(format!("updated-by-thread-{}", i));
                        Ok(())
                    })
                    .unwrap();
                })
            };

            handles.push(handle);
        }

        // Wait for all threads to complete
        for handle in handles {
            handle.join().unwrap();
        }

        // Verify final state is consistent
        let final_agent = load_agent_metadata(&config, "mixed-ops-test").unwrap();
        assert!(final_agent.container_id.is_some());
    }

    #[test]
    fn test_validate_agent_name() {
        // Valid names
        assert!(validate_agent_name("valid-name").is_ok());
        assert!(validate_agent_name("valid_name").is_ok());
        assert!(validate_agent_name("valid123").is_ok());
        assert!(validate_agent_name("a").is_ok());

        // Invalid names
        assert!(validate_agent_name("").is_err());
        assert!(validate_agent_name("invalid name").is_err());
        assert!(validate_agent_name("invalid/name").is_err());
        assert!(validate_agent_name("invalid.name").is_err());
        assert!(validate_agent_name(&"a".repeat(65)).is_err());
    }

    #[test]
    fn test_format_duration() {
        let now = Utc::now();
        
        // Just now
        assert_eq!(format_duration(now), "just now");
        
        // Minutes ago
        assert_eq!(format_duration(now - chrono::Duration::minutes(5)), "5m ago");
        
        // Hours ago
        assert_eq!(format_duration(now - chrono::Duration::hours(3)), "3h ago");
        
        // Days ago
        assert_eq!(format_duration(now - chrono::Duration::days(2)), "2d ago");
    }
}
