name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        # For PRs, check the PR HEAD instead of merge commit
        ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
    
    - name: Check conventional commits
      uses: cocogitto/cocogitto-action@v3
      # For PRs, check all commits in the PR. For pushes, only check since latest tag
      with:
        check-latest-tag-only: ${{ github.event_name != 'pull_request' }}
    
    - uses: dtolnay/rust-toolchain@stable
    
    - run: cargo fmt --all -- --check
    - run: cargo clippy --all-targets -- -D warnings  
    - run: cargo test

  docker-test:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'test-docker') || github.event_name == 'push'
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: docker build -t crowdcontrol:latest ./container/
    - run: cargo test --test integration_test -- --ignored --test-threads=1